### ISSUE TITLE
Users want to use a simple app

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/store-front-with-api#3]
## 💰 Motivation

A great app = simple functionality 

## 📐 Plan

Implement design without functionality 

## ✅ Task List
- [ ] Create React project
- [ ] Plan Pages and components 
- [ ] Render pages without functionality
